sudo: required

services:
  - docker

before_install:
  # Build the Docker image using Dockerfile.dev
  - docker build -t hemtamang9/docker-react -f Dockerfile.dev .

script:
  # Run your test suite inside the Docker container
  - docker run -e CI=true hemtamang9/docker-react npm run test
